# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests for iOS Project"
  lane :tests do
    run_tests(
      clean: true,
      output_directory: "./test_result/",
      project: "iOS Project.xcodeproj",
      cloned_source_packages_path: "./SourcePackages"
    )
  end
end
